# Site information
lang: en_GB 
title: insightsdude.uk
email: info@insightsdude.uk
description: Passionate about making data easy
url: "https://insightsdude.uk" 

#Post processing config
permalink: /:year/:month/:day/:title:output_ext
show_excerpts: true

#Social media settings
twitter_username: artislismanis
github_username:  artislismanis

#Google Analytics Settings
google_analytics: "UA-140855486-1"

# Theme configuration
theme: minima
minima:
  date_format: "%Y-%m-%d"

# Enable installed plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

# Override default excludes
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - .gitignore
